### ISSUE TITLE
Could you please upload the "240228_SC2_CDS.fasta" and "240228_B236_CDS.fasta" files?

### ISSUE THREAD

**Issue by liamxg** [TheSatoLab/B236_full#1]
Dear @chainorato,

Could you please upload the "240228_SC2_CDS.fasta" and "240228_B236_CDS.fasta" files?
Thanks.

**Comment by chainorato** [comment]
Hi @liamxg 

Sure. I have uploaded the requested files

**Comment by liamxg** [comment]
Hi @chainorato,
Cool!
